### 3. **docker-compose.yml**
version: '3.8'

services:
  db:
    image: postgres:15
    container_name: inventory_db
    environment:
      POSTGRES_DB: inventory_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - inventory_network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: inventory_backend
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/inventory_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    networks:
      - inventory_network

volumes:
  postgres_data:

networks:
  inventory_network:
    driver: bridge
